# Generated by Django 4.2.9 on 2024-05-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
